import shutil
import os
a= ['31-phillip-lim',
 'acne-studios-pre',
 'agnona-pre',
 'akris',
 'alberta-ferretti',
 'alessandra-rich',
 'alexander-mcqueen',
 'alexander-wang',
 'alexa_chung',
 'altuzarra',
 'andreas-kronthaler-for-vivienne-westwood1',
 'ann-demeulemeester',
 'anna-sui',
 'anya-hindmarch',
 'area',
 'ashish',
 'ashley-williams',
 'atlein',
 'balenciaga',
 'balmain',
 'baum-und-pferdgarten',
 'beautiful-people',
 'bora-aksu',
 'boss',
 'brandon-maxwell',
 'brock-collection-pre',
 'brogger',
 'burberry',
 'by-malene-birger',
 'byblos',
 'calvin-klein-collection',
 'carolina-herrera',
 'cecilie-bahnsen',
 'celine',
 'central-saint-martins-ba',
 'chalayan',
 'chanel',
 'chloe',
 'christian-dior',
 'christian-siriano',
 'christopher-kane',
 'coach-1941-pre',
 'comme-des-garcons',
 'courreges-pre',
 'david-koma',
 'delpozo-pre',
 'diane-von-furstenberg',
 'dilara-findikoglu',
 'dodo-bar-or',
 'dolce-gabbana',
 'dondup-pre',
 'dries-van-noten',
 'dusan',
 'eckhaus-latta',
 'elie-saab',
 'emilia-wickstead',
 'emporio-armani',
 'erdem',
 'ermanno-scervino',
 'escada-pre',
 'etro',
 'eudon-choi',
 'fashion-east-asai',
 'fashion-east-charlotte-knowles',
 'fashion-east-yuhan-wang',
 'fendi',
 'gabriela-hearst-pre',
 'galvan',
 'ganni',
 'gareth-pugh',
 'giambattista-valli',
 'giorgio-armani',
 'givenchy',
 'graduate-fashion-week-gala',
 'gucci',
 'haider-ackermann',
 'halpern',
 'hermes',
 'holland-and-holland',
 'house-of-holland',
 'hugo',
 'huishan-zhang',
 'isa-arfen-pre',
 'isabel-marant',
 'issey-miyake',
 'j-js-lee',
 'jacquemus',
 'jasper-conran',
 'jeremy-scott',
 'jil-sander',
 'jlindeberg',
 'jm-davidson',
 'jonathan-simkhai-pre',
 'joseph',
 'junya-watanabe',
 'jw-anderson',
 'kate-spade',
 'kiko-kostadinov',
 'kith',
 'koche',
 'lemaire',
 'loewe',
 'longchamp',
 'louis-vuitton',
 'magda-butrym',
 'maison-margiela-pre',
 'marc-jacobs',
 'marco-de-vincenzo',
 'margaret-howell',
 'marine-serre-brand',
 'mark-fast',
 'markus-lupfer',
 'marni',
 'marques-almeida-brand',
 'marta-jakubowski',
 'mary-katrantzou',
 'maryam-nassir-zadeh',
 'matthew-adams-dolan',
 'matty-bovan',
 'max-mara',
 'michael-kors-collection-pre',
 'missoni',
 'miu-miu',
 'mm6-maison-margiela-pre',
 'molly-goddard',
 'moncler',
 'monse',
 'moschino',
 'mother-of-pearl-pre',
 'msgm',
 'mugler',
 'mulberry',
 'nanushka',
 'natasha-zinko',
 'nicholas-kirkwood',
 'no21',
 'off-white-pre',
 'opening-ceremony',
 'oscar-de-la-renta',
 'osman',
 'ottolinger',
 'paco-rabanne',
 'palmer-harding-pre',
 'paul-joe',
 'petar-petrov',
 'peter-pilotto',
 'philipp-plein-pre',
 'philosophy-di-lorenzo-serafini',
 'plein-sport',
 'ports-1961',
 'prabal-gurung',
 'prada',
 'preen-by-thornton-bregazzi',
 'pringle-of-scotland',
 'proenza-schouler',
 'r13',
 'rag-bone',
 'ralph-lauren',
 'redemption',
 'rejina-pyo',
 'richard-malone',
 'richard-quinn',
 'rick-owens',
 'roberta-einer',
 'roberto-cavalli',
 'rochas',
 'rodarte',
 'roksanda-pre',
 'roland-mouret',
 'romeo-hunte',
 'rosetta-getty-pre',
 'royal-college-of-art',
 'ryan-lo',
 'sacai',
 'sadie-williams',
 'saint-laurent',
 'saks-potts',
 'salvatore-ferragamo',
 'schiaparelli',
 'self-portrait',
 'sharon-wauchob',
 'sies-marjan',
 'simone-rocha',
 'sonia-rykiel',
 'sportmax',
 'stella-mccartney',
 'stine-goya',
 'supriya-lele',
 'symonds-pearmain',
 'telfar',
 'temperley-london',
 'the-row',
 'theory-pre',
 'thom-browne',
 'tibi-pre',
 'tiziano-guardini',
 'tods',
 'toga',
 'tom-ford',
 'tommy-hilfiger',
 'toogood',
 'tory-burch',
 'valentin-yudashkin',
 'valentino',
 'vaquera',
 'versace',
 'victoria-beckham',
 'vivienne-westwood',
 'xu-zhi',
 'yang-li',
 'yohji-yamamoto',
 'zimmermann']

count=1
# temp='./sample/'+str(a[0])
# print(temp)
# temp2=os.listdir(temp)
# print(temp2)
# print(len(temp2))


for i in range(0, 212):
 dir_select='./sample/'+str(a[i])
 dir_len=os.listdir(dir_select)
 #print(len(dir_len))
 print(dir_select, len(dir_len), i)

 for j in range(1, len(dir_len)+1):




  if j<10:
   shutil.copy(dir_select+'/00000' + str(j) + '.jpg', './sample2/' + str(count) + '.jpg')
  elif j<100:
   shutil.copy(dir_select + '/0000' + str(j) + '.jpg', './sample2/' + str(count) + '.jpg')
  elif j<1000:
   shutil.copy(dir_select + '/000' + str(j) + '.jpg', './sample2/' + str(count) + '.jpg')

  count = count + 1